### ISSUE TITLE
Contrast on the initial pop up

### ISSUE THREAD

**Issue by fellyph** [ErosMLima/Dev_Finances#1]
The initial pop red color doesn't have a good contrast and the transparent background from the cancel button makes it  harder to read when has a element behind the button

![Screen Shot 2021-03-06 at 10 49 18](https://user-images.githubusercontent.com/330792/110204288-25c17280-7e6a-11eb-80e8-f0ad464627ee.png)

**Comment by ErosMLima** [comment]
In the next version it's gonna be done!

**Comment by ErosMLima** [comment]
In the next version it's gonna be done! Thanks for open here! a lot
